spring.application.name=ms-bff
server.port=8085

MS_DATOS_URL=${MS_DATOS_URL:http://localhost:8081}
MS_KPI_URL=${MS_KPI_URL:http://localhost:8082}
MS_REPORTES_URL=${MS_REPORTES_URL:http://localhost:8083}

# Circuit Breaker config
resilience4j.circuitbreaker.instances.bff-dashboard.sliding-window-size=5
resilience4j.circuitbreaker.instances.bff-dashboard.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.bff-dashboard.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.bff-sucursal.sliding-window-size=5
resilience4j.circuitbreaker.instances.bff-sucursal.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.bff-sucursal.wait-duration-in-open-state=10s