spring.application.name=ms-bff
server.port=8085

# URLs de los microservicios (dentro de Docker usa nombres de contenedor)
MS_DATOS_URL=${MS_DATOS_URL:http://localhost:8081}
MS_KPI_URL=${MS_KPI_URL:http://localhost:8082}
MS_REPORTES_URL=${MS_REPORTES_URL:http://localhost:8083}